version: "2.2"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save "" --appendonly no

  # sentiment_endpoint:
  #   build: ai/sentiment_classifier/
  #   image: topic_generation:latest
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./ai/sentiment_classifier/app:/app
  #   command: "python main.py"

  backend:
    build: backend/
    image: backend:latest
    ports:
      - 7001:7001
    volumes:
      - ./backend/app:/app
    depends_on:
      - cache
    command: "python main.py"

# hi