version: "2.2"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save "" --appendonly no

  backend:
    build: backend/
    image: backend:latest
    ports:
      - 7001:7001
    volumes:
      - ./backend/app:/app
    depends_on:
      - cache
    command: "uvicorn main:app --host 0.0.0.0 --port 7001"

  frontend:
    build: frontend/
    image: frontend:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
    stdin_open: true
    tty: true

  # bertopic:
  #   build: ./ai/bertopic
  #   image: bertopic:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - PORT=8080

  # distilbert:
  #   build: ./ai/distilbert
  #   image: distilbert:latest
  #   ports:
  #      - 8081:8081
  #   environment:
  #     - PORT=8081

  model:
    build: models/
    image: models:latest
    volumes:
      - ./models/app/:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: "python main.py"
