version: '1'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save "" --appendonly no
  backend:
    build: backend/
    image: backend:latest
    ports:
      - 7001:7001
      - 8080:8080
    volumes:
      - ./backend/app:/app
    depends_on:
      - cache
    command: "python main.py"

# hi