version: "2.2"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save "" --appendonly no

  backend:
    build: backend/
    image: backend:latest
    ports:
      - 7001:7001
    volumes:
      - ./backend/app:/app
    depends_on:
      - cache
    command: "python main.py"

  # bertopic:
  #   build: ./ai/bertopic
  #   image: bertopic:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - PORT=8080

  # distilbert:
  #   build: ./ai/distilbert
  #   image: distilbert:latest
  #   ports:
  #      - 8081:8081
  #   environment:
  #     - PORT=8081

  model:
    build: models/
    image: models:latest
    volumes:
      - ./models/app/:/app
    ports:
      - 8000:8000
    command: "python main.py"
